version: "3.9"

services:
  inviter:
    build:
      context: ./inviter
    env_file:
      - .env
    volumes:
      - ./sessions:/app/sessions
    networks:
      - parser_default

networks:
  parser_default:
    external: true
